#include "helper.h"
#include "visual.h"
#include <stdio.h>


void write_vtkFile(const char *szProblem,
		 int    timeStepNumber,
		 double xlength,
                 double ylength,
                 int    imax,
                 int    jmax,
		 double dx,
		 double dy,
                 double **U,
                 double **V,
                 double **P
) {
  
  int i,j;
  char szFileName[80];
  FILE *fp=NULL;
  sprintf( szFileName, "%s.%i.vtk", szProblem, timeStepNumber );
  fp = fopen( szFileName, "w");
  if( fp == NULL )		       
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to open %s", szFileName );
    ERROR( szBuff );
    return;
  }

  write_vtkHeader( fp, imax, jmax, dx, dy);
  write_vtkPointCoordinates(fp, imax, jmax, dx, dy);

  fprintf(fp,"POINT_DATA %i \n", (imax+1)*(jmax+1) );
  fprintf(fp,"\n");
  fprintf(fp, "VECTORS velocity float\n");
  for(j = 0; j < jmax+1; j++) {
    for(i = 0; i < imax+1; i++) {
      fprintf(fp, "%f %f 0\n", (U[i][j] + U[i][j+1]) * 0.5, (V[i][j] + V[i+1][j]) * 0.5 );
    }
  }

  fprintf(fp,"\n");
  fprintf(fp,"CELL_DATA %i \n", ((imax)*(jmax)) );
  fprintf(fp, "SCALARS pressure float 1 \n"); 
  fprintf(fp, "LOOKUP_TABLE default \n");
  for(j = 1; j < jmax+1; j++) {
    for(i = 1; i < imax+1; i++) {
      fprintf(fp, "%f\n", P[i][j] );
    }
  }

  if( fclose(fp) )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to close %s", szFileName );
    ERROR( szBuff );
  }
}


void write_vtkHeader( FILE *fp, int imax, int jmax, 
                      double dx, double dy) {
  if( fp == NULL )		       
  {
    char szBuff[80];
    sprintf( szBuff, "Null pointer in write_vtkHeader" );
    ERROR( szBuff );
    return;
  }

  fprintf(fp,"# vtk DataFile Version 2.0\n");
  fprintf(fp,"generated by CFD-lab course output (written by Tobias Neckel) \n");
  fprintf(fp,"ASCII\n");
  fprintf(fp,"\n");	
  fprintf(fp,"DATASET STRUCTURED_GRID\n");
  fprintf(fp,"DIMENSIONS  %i %i 1 \n", imax+1, jmax+1);
  fprintf(fp,"POINTS %i float\n", (imax+1)*(jmax+1) );
  fprintf(fp,"\n");
}


void write_vtkPointCoordinates( FILE *fp, int imax, int jmax, 
                      double dx, double dy) {
  double originX = 0.0;  
  double originY = 0.0;

  int i = 0;
  int j = 0;

  for(j = 0; j < jmax+1; j++) {
    for(i = 0; i < imax+1; i++) {
      fprintf(fp, "%f %f 0\n", originX+((i+1)*dx), originY+((j+1)*dy) );
    }
  }
}



void write_vtkParticleFile(const char *szProblem,
                   int    timeStepNumber,
                   double xlength,
                   double ylength,
                   int    imax,
                   int    jmax,
                   int    N,
                   double dx,
                   double dy,
                   struct particleline *Particlelines,
                   int **flag)
{

    int length=0;
    char szFileName[80];
    FILE *fp=NULL;
    sprintf( szFileName, "%s.particle.%i.vtk", szProblem, timeStepNumber );
    fp = fopen( szFileName, "w");
    if( fp == NULL )
    {
        char szBuff[80];
        sprintf( szBuff, "Failed to open %s", szFileName );
        ERROR( szBuff );
        return;
    }
    /*calculate the number of the particles*/
    int i,j;
    for(int k = 0; k < N; k++)
    {
      if(Particlelines[k].Particles!=NULL)
      {
      struct particle *temp = Particlelines[k].Particles;
      for(int p = 0; p < Particlelines[k].length; p++)
      {
        double x_pos = temp->x;
        double y_pos = temp->y;

        i = (int)(x_pos/dx);
        j = (int)(y_pos/dy);

        if((flag[i][j]&(1<<1|1<<2))==0)
        {
        if (x_pos < imax * dx && y_pos < jmax * dy && x_pos > 0 && y_pos > 0 )
        {
          length++;
        }
        }
        temp = temp->next;
      }
      }
      
    }

    write_vtkParticleHeader( fp, imax, jmax, length);
    write_vtkParticleCoordinates(fp,N,Particlelines, imax, jmax, dx, dy, flag);

    if( fclose(fp) )
    {
        char szBuff[80];
        sprintf( szBuff, "Failed to close %s", szFileName );
        ERROR( szBuff );
    }
}


void write_vtkParticleHeader( FILE *fp, int imax, int jmax,int length)
{
    if( fp == NULL )
    {
        char szBuff[80];
        sprintf( szBuff, "Null pointer in write_vtkHeader" );
        ERROR( szBuff );
        return;
    }

    fprintf(fp,"# vtk DataFile Version 2.0\n");
    fprintf(fp,"ASCII\n");
    fprintf(fp,"\n");
    fprintf(fp,"DATASET UNSTRUCTURED_GRID\n");
    fprintf(fp,"POINTS %i float\n", length);
    fprintf(fp,"\n");
}



void write_vtkParticleCoordinates( FILE *fp,int N,struct particleline *Particlelines, int imax,
                   int    jmax,
                   double dx,
                   double dy,
                   int **flag)
{
  int i,j;
    for(int k = 0; k < N; k++)
    {
      if(Particlelines[k].Particles!=NULL)
      {
      struct particle *temp = Particlelines[k].Particles;
      for(int p = 0; p < Particlelines[k].length; p++)
      {
        double x_pos = temp->x;
        double y_pos = temp->y;

        i = (int)(x_pos/dx);
        j = (int)(y_pos/dy);

        if((flag[i][j]&(1<<1|1<<2))==0)
        {
        if (x_pos < imax * dx && y_pos < jmax * dy && x_pos > 0 && y_pos > 0 )
        {
          fprintf(fp, "%f %f 0\n", temp->x, temp->y);
        }
        }
          temp = temp->next;
      }
      }
      
    }

}
